### ISSUE TITLE
Eigen not found 

### ISSUE THREAD

**Issue by hayday100** [ROBOTIS-GIT/humanoid_navigation#9]
I have installed Eigen3 by command 
sudo apt-get install libeigen3-dev
But still receive the following error during catkin_make

CMake Error at humanoid_navigation/humanoid_localization/CMakeLists.txt:7 (find_package):
  By not providing "FindEigen.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen" with any of
  the following names:

    EigenConfig.cmake
    eigen-config.cmake

  Add the installation prefix of "Eigen" to CMAKE_PREFIX_PATH or set
  "Eigen_DIR" to a directory containing one of the above files.  If "Eigen"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by robotpilot** [comment]
Hi @hayday100,

What development environment do you use with this package?
I've just re-tested it in the development environment below, but I was able to build and use it without problems. 

- Ubuntu 16.04
- ROS Kinetic Kame

In addition, you can install this package as a binary. Then the next four packages are installed: footstep_planner, gridmap_2d, humanoid_localization, humanoid_planner_2d

```
sudo apt-get install ros-kinetic-humanoid-navigation
```

**Comment by hayday100** [comment]
Hi @robotpilot:

Thanks for your quick reply. You are exactly right about my environment of Ubuntu 16.04 with ROS Kinetic.  I followed the instructions below and fixed the Eigen problem.  

https://answers.ros.org/question/213872/eigenconfigcmake-not-found-ros-indigo/

But now I run into a new error at linking time.  
`[  5%] Building CXX object humanoid_navigation/humanoid_localization/CMakeFiles/motionmodel.dir/src/MotionModel.cpp.o
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /usr/include/boost/format/alt_sstream.hpp:21,
                 from /usr/include/boost/format/internals.hpp:23,
                 from /usr/include/boost/format.hpp:38,
                 from /usr/include/boost/math/policies/error_handling.hpp:31,
                 from /usr/include/boost/math/special_functions/round.hpp:14,
                 from /opt/ros/kinetic/include/ros/time.h:58,
                 from /opt/ros/kinetic/include/ros/ros.h:38,
                 from /opt/ros/kinetic/include/humanoid_localization/MapModel.h:28,
                 from /home/chen/catkin_ws/src/humanoid_navigation/humanoid_localization/src/MapModel.cpp:24:
/usr/include/boost/smart_ptr/shared_ptr.hpp: In instantiation of ‘boost::shared_ptr<T>::shared_ptr(Y*) [with Y = octomap::AbstractOcTree; T = octomap::OcTree]’:
/usr/include/boost/smart_ptr/shared_ptr.hpp:620:9:   required from ‘void boost::shared_ptr<T>::reset(Y*) [with Y = octomap::AbstractOcTree; T = octomap::OcTree]’
/home/chen/catkin_ws/src/humanoid_navigation/humanoid_localization/src/MapModel.cpp:275:53:   required from here
/usr/include/boost/smart_ptr/shared_ptr.hpp:347:47: error: invalid conversion from ‘octomap::AbstractOcTree*’ to ‘boost::shared_ptr<octomap::OcTree>::element_type* {aka octomap::OcTree*}’ [-fpermissive]
     explicit shared_ptr( Y * p ): px( p ), pn() // Y must be complete
                                               ^
humanoid_navigation/humanoid_localization/CMakeFiles/mapmodel.dir/build.make:62: recipe for target 'humanoid_navigation/humanoid_localization/CMakeFiles/mapmodel.dir/src/MapModel.cpp.o' failed
make[2]: *** [humanoid_navigation/humanoid_localization/CMakeFiles/mapmodel.dir/src/MapModel.cpp.o] Error 1
CMakeFiles/Makefile2:11713: recipe for target 'humanoid_navigation/humanoid_localization/CMakeFiles/mapmodel.dir/all' failed
make[1]: *** [humanoid_navigation/humanoid_localization/CMakeFiles/mapmodel.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Linking CXX shared library /home/chen/catkin_ws/devel/lib/libmotionmodel.so
[  5%] Built target motionmodel
[  5%] Linking CXX shared library /home/chen/catkin_ws/devel/lib/libendpointmodel.so
[  5%] Linking CXX shared library /home/chen/catkin_ws/devel/lib/libobservationmodel.so
[  5%] Built target observationmodel
[  5%] Built target endpointmodel
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`

**Comment by robotpilot** [comment]
Hi again @hayday100,

There are a few things I want to check out. Did you receive the source code from the correct repository? The humanoid_navigation package has a different repository and different Maintainer depending on the ROS version. From the Kinetic version, I manage it. The address for git clone is:
```
git clone https://github.com/ROBOTIS-GIT/humanoid_navigation.git
```

If this is not a problem I don't know if you get an error when compiling.

We use both Jenkins CI and Travis CI to find the dependency of the source code and the problem depending on the development environment as follows, and it is being built without problems until now.

- Jenkins CI 
http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__humanoid_navigation__ubuntu_xenial_amd64__binary/

- Travis CI
https://travis-ci.org/ROBOTIS-GIT/humanoid_navigation

**Comment by hayday100** [comment]
Hi there @robotpilot ,

Since my ubuntu is Xenial and ROS is Kinetic, does that mean I can download a binary and skip the catkin_make for humanoid_navigation?  If so, how?  I do run into another dependency problem at 93% after git clone the source code you provided above and I am a little tired of solving this issue myself.

`Scanning dependencies of target footstep_planner_node
[ 93%] Building CXX object humanoid_navigation/footstep_planner/CMakeFiles/footstep_planner_node.dir/src/footstep_planner.cpp.o
[ 93%] Linking CXX executable /home/chen/catkin_ws/devel/lib/footstep_planner/footstep_planner_node
[ 93%] Linking CXX executable /home/chen/catkin_ws/devel/lib/footstep_planner/footstep_navigation_node
[ 93%] Linking CXX shared library /home/chen/catkin_ws/devel/lib/librobotis_controller.so
/home/chen/catkin_ws/devel/lib/libfootstep_planner.so: undefined reference to `SBPL2DGridSearch::SBPL2DGridSearch(int, int, float)'
collect2: error: ld returned 1 exit status
humanoid_navigation/footstep_planner/CMakeFiles/footstep_planner_node.dir/build.make:200: recipe for target '/home/chen/catkin_ws/devel/lib/footstep_planner/footstep_planner_node' failed
make[2]: *** [/home/chen/catkin_ws/devel/lib/footstep_planner/footstep_planner_node] Error 1
CMakeFiles/Makefile2:9972: recipe for target 'humanoid_navigation/footstep_planner/CMakeFiles/footstep_planner_node.dir/all' failed
make[1]: *** [humanoid_navigation/footstep_planner/CMakeFiles/footstep_planner_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/chen/catkin_ws/devel/lib/libfootstep_planner.so: undefined reference to `SBPL2DGridSearch::SBPL2DGridSearch(int, int, float)'
collect2: error: ld returned 1 exit status
humanoid_navigation/footstep_planner/CMakeFiles/footstep_navigation_node.dir/build.make:200: recipe for target '/home/chen/catkin_ws/devel/lib/footstep_planner/footstep_navigation_node' failed
make[2]: *** [/home/chen/catkin_ws/devel/lib/footstep_planner/footstep_navigation_node] Error 1
CMakeFiles/Makefile2:9896: recipe for target 'humanoid_navigation/footstep_planner/CMakeFiles/footstep_navigation_node.dir/all' failed
make[1]: *** [humanoid_navigation/footstep_planner/CMakeFiles/footstep_navigation_node.dir/all] Error 2
[ 93%] Built target robotis_controller
[ 93%] Linking CXX executable /home/chen/catkin_ws/devel/lib/footstep_planner/footstep_planner_walls
/home/chen/catkin_ws/devel/lib/libfootstep_planner.so: undefined reference to `SBPL2DGridSearch::SBPL2DGridSearch(int, int, float)'
collect2: error: ld returned 1 exit status
humanoid_navigation/footstep_planner/CMakeFiles/footstep_planner_walls.dir/build.make:200: recipe for target '/home/chen/catkin_ws/devel/lib/footstep_planner/footstep_planner_walls' failed
make[2]: *** [/home/chen/catkin_ws/devel/lib/footstep_planner/footstep_planner_walls] Error 1
CMakeFiles/Makefile2:9934: recipe for target 'humanoid_navigation/footstep_planner/CMakeFiles/footstep_planner_walls.dir/all' failed
make[1]: *** [humanoid_navigation/footstep_planner/CMakeFiles/footstep_planner_walls.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`

**Comment by robotpilot** [comment]
Hi @hayday100,
Of course, you can install and use the binary file with the following command without any build work.
```sh
sudo apt-get install ros-kinetic-humanoid-navigation 
```

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
